package com.STFAS.mapper;

import com.STFAS.dto.Warehouse.request.WarehouseRequestDto;
import com.STFAS.dto.Warehouse.response.WarehouseResponseDto;
import com.STFAS.entity.Warehouse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface WarehouseMapper {

    // Request -> Entity
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    Warehouse toEntity(WarehouseRequestDto dto);

    // Entity -> Response
    WarehouseResponseDto toDto(Warehouse entity);
}